---

- name: apt key for NVIDIA is added
  apt_key:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_repo_distarch }}/7fa2af80.pub"
    id: 7fa2af80
    state: present

- name: NVIDIA CUDA repository is registered
  apt_repository:
    repo: 'deb http://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_repo_distarch }} /'
    state: present
    filename: cuda
    update_cache: no
  notify: Update apt cache

- name: NVIDIA Machine Learning repository is registered
  apt_repository:
    repo: 'deb http://developer.download.nvidia.com/compute/machine-learning/repos/{{ nvidia_repo_distarch }} /'
    state: present
    filename: machine-learning
    update_cache: no
  when: enable_nvidia_machine_learning_repo
  notify: Update apt cache
